### ISSUE TITLE
Error starting v3.0.0

### ISSUE THREAD

**Issue by jlambert121** [eifinger/hass-here-weather#190]
Thanks for this update and your work on it - it was way more than I realized!  I updated to the latest version this morning and ran into one hiccup.

## Version of the custom_component

3.0.0

## Configuration

```
Unexpected error fetching here_weather data: 'moonSet'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/here_weather/__init__.py", line 88, in _async_update_data
    return await self._get_data()
  File "/config/custom_components/here_weather/__init__.py", line 102, in _get_data
    return extract_data_from_payload_for_product_type(
  File "/config/custom_components/here_weather/__init__.py", line 112, in extract_data_from_payload_for_product_type
    return parse_time_as_utc(astronomy_data(data["astronomyForecasts"][0]))
  File "/config/custom_components/here_weather/__init__.py", line 142, in astronomy_data
    return astronomy_data_with_utc(ammended_data)
  File "/config/custom_components/here_weather/__init__.py", line 166, in astronomy_data_with_utc
    element["moonSet"], element["time"]
KeyError: 'moonSet'
```

## Describe the bug

After updating to version 3.0.0, the following error prevents the integration from starting.  Commenting lines 165-167 in `__init__.py` allows the integration to start and fetch weather.

## Debug log

```text

Add your logs here.

```

**Comment by eifinger** [comment]
Merry christmas. Thanks for the testing I can reproduce the issue and will investigate

**Comment by eifinger** [comment]
The error should be gone.
